// Builds the one-step layout setup scripts from extras/userChrome.css and
// extras/user.js, so they always ship the current files:
//   extras/setup/arc-setup.txt  (macOS, Linux; downloaded as arc-setup.sh)
//   extras/setup/arc-setup.ps1  (Windows)
// Run: npm run build:setup
import fs from "node:fs";

const css = fs.readFileSync("extras/userChrome.css", "utf8").trimEnd();
const prefs = fs.readFileSync("extras/user.js", "utf8").trimEnd();
const keys = fs.readFileSync("extras/setup-keys.sh.txt", "utf8").trimEnd();

for (const [name, text] of [["css", css], ["prefs", prefs]]) {
  if (text.includes("ARC_EOF") || /^'@/m.test(text)) throw new Error(`${name} contains a heredoc terminator`);
}

const sh = `#!/usr/bin/env bash
# Arc for Firefox: give Arc the whole window (macOS & Linux).
#
# Adds Arc's layout to the Firefox profile that has Arc installed:
#   <profile>/chrome/userChrome.css  hides Firefox's tab strip and toolbar
#   <profile>/user.js                turns the stylesheet on, horizontal tabs,
#                                    opens Arc at startup
#   <profile>/customKeys.json        clears Firefox's Cmd/Ctrl+T and Cmd/Ctrl+W
#                                    so Arc can handle them
# Your own CSS and prefs are kept: Arc only manages its marked block.
#
# Usage:  bash arc-setup.sh              set up (or update)
#         bash arc-setup.sh --uninstall  remove Arc's blocks again
# Generated by scripts/build-setup.mjs; edit extras/ instead.
set -euo pipefail

ADDON_ID="arc@sidebar"
CSS_BEGIN="/* >>> Arc for Firefox >>> */"
CSS_END="/* <<< Arc for Firefox <<< */"
JS_BEGIN="// >>> Arc for Firefox >>>"
JS_END="// <<< Arc for Firefox <<<"

UNINSTALL=0
[ "\${1:-}" = "--uninstall" ] && UNINSTALL=1

case "$(uname -s)" in
  Darwin) ROOTS=("$HOME/Library/Application Support/Firefox/Profiles") ;;
  *) ROOTS=("$HOME/.mozilla/firefox" "$HOME/snap/firefox/common/.mozilla/firefox" "$HOME/.var/app/org.mozilla.firefox/.mozilla/firefox") ;;
esac

# Every Firefox profile folder (has prefs.js); Arc's first.
ARC=()
OTHER=()
for root in "\${ROOTS[@]}"; do
  [ -d "$root" ] || continue
  for dir in "$root"/*/; do
    dir="\${dir%/}"
    [ -f "$dir/prefs.js" ] || continue
    if grep -q "\\"id\\":\\"$ADDON_ID\\"" "$dir/extensions.json" 2>/dev/null; then ARC+=("$dir"); else OTHER+=("$dir"); fi
  done
done

if [ \${#ARC[@]} -gt 0 ]; then
  CANDIDATES=("\${ARC[@]}")
else
  echo "No Firefox profile with Arc installed was found. Install Arc first, or pick a profile:"
  CANDIDATES=("\${OTHER[@]}")
fi
[ \${#CANDIDATES[@]} -gt 0 ] || { echo "No Firefox profiles found." >&2; exit 1; }

PROFILE="\${CANDIDATES[0]}"
if [ \${#CANDIDATES[@]} -gt 1 ]; then
  echo "Several Firefox profiles found:"
  i=1
  for p in "\${CANDIDATES[@]}"; do echo "  $i) $(basename "$p")"; i=$((i + 1)); done
  printf "Which one? [1-%s] " "\${#CANDIDATES[@]}"
  read -r pick < /dev/tty
  case "$pick" in ''|*[!0-9]*) echo "Not a number." >&2; exit 1 ;; esac
  [ "$pick" -ge 1 ] && [ "$pick" -le \${#CANDIDATES[@]} ] || { echo "Out of range." >&2; exit 1; }
  PROFILE="\${CANDIDATES[$((pick - 1))]}"
fi

# Replace (or remove) the marked block in a file, keeping everything else.
write_block() {
  local file="$1" begin="$2" end="$3" content="$4" tmp
  mkdir -p "$(dirname "$file")"
  # A symlinked file belongs to something else (a dotfiles repo, or Arc's own
  # source in a development profile): writing the block would edit that.
  if [ -L "$file" ]; then
    echo "Skipping $file: it is a symlink, so it is managed elsewhere."
    return 0
  fi
  touch "$file"
  tmp="$(mktemp)"
  # Drop the old block (and trailing blank lines), keep everything else.
  awk -v b="$begin" -v e="$end" '
    index($0, b) { skip = 1 }
    !skip { if ($0 == "") blank++; else { while (blank > 0) { print ""; blank-- } print } }
    index($0, e) { skip = 0 }' "$file" > "$tmp"
  if [ "$UNINSTALL" -eq 0 ]; then
    [ -s "$tmp" ] && printf '\\n' >> "$tmp"
    printf '%s\\n%s\\n%s\\n' "$begin" "$content" "$end" >> "$tmp"
  fi
  cat "$tmp" > "$file"
  rm -f "$tmp"
}

# read -d '' (not $(cat <<...)): macOS bash 3.2 misparses quotes inside $( heredoc ).
IFS= read -r -d '' CSS <<'ARC_EOF' || true
${css}
ARC_EOF
CSS="\${CSS%$'\\n'}"

IFS= read -r -d '' PREFS <<'ARC_EOF' || true
${prefs}
ARC_EOF
PREFS="\${PREFS%$'\\n'}"

${keys}

write_block "$PROFILE/chrome/userChrome.css" "$CSS_BEGIN" "$CSS_END" "$CSS"
write_block "$PROFILE/user.js" "$JS_BEGIN" "$JS_END" "$PREFS"

if [ "$UNINSTALL" -eq 1 ]; then
  echo "Removed Arc's layout from $(basename "$PROFILE")."
  echo "Restart Firefox. user.js prefs already applied stay until you change them in about:config."
else
  echo "Arc's layout is set up in $(basename "$PROFILE")."
  echo "Quit Firefox completely and open it again."
fi
`;

const ps1 = `# Arc for Firefox: give Arc the whole window (Windows).
#
# Adds Arc's layout to the Firefox profile that has Arc installed:
#   <profile>\\chrome\\userChrome.css  hides Firefox's tab strip and toolbar
#   <profile>\\user.js                turns the stylesheet on, horizontal tabs,
#                                    opens Arc at startup
#   <profile>\\customKeys.json        clears Firefox's Ctrl+T and Ctrl+W so Arc
#                                    can handle them
# Your own CSS and prefs are kept: Arc only manages its marked block.
#
# Usage:  powershell -ExecutionPolicy Bypass -File arc-setup.ps1             set up (or update)
#         powershell -ExecutionPolicy Bypass -File arc-setup.ps1 -Uninstall  remove Arc's blocks
# Generated by scripts/build-setup.mjs; edit extras/ instead.
param([switch]$Uninstall)
$ErrorActionPreference = "Stop"

$AddonId = "arc@sidebar"
$CssBegin = "/* >>> Arc for Firefox >>> */"
$CssEnd = "/* <<< Arc for Firefox <<< */"
$JsBegin = "// >>> Arc for Firefox >>>"
$JsEnd = "// <<< Arc for Firefox <<<"

$root = Join-Path $env:APPDATA "Mozilla\\Firefox\\Profiles"
if (-not (Test-Path $root)) { Write-Error "No Firefox profiles found in $root" }

$all = @(Get-ChildItem $root -Directory | Where-Object { Test-Path (Join-Path $_.FullName "prefs.js") })
$arc = @($all | Where-Object {
  $ext = Join-Path $_.FullName "extensions.json"
  (Test-Path $ext) -and ((Get-Content $ext -Raw) -match [regex]::Escape('"id":"' + $AddonId + '"'))
})

if ($arc.Count -gt 0) { $candidates = $arc } else {
  Write-Host "No Firefox profile with Arc installed was found. Install Arc first, or pick a profile:"
  $candidates = $all
}
if ($candidates.Count -eq 0) { Write-Error "No Firefox profiles found." }

$target = $candidates[0]
if ($candidates.Count -gt 1) {
  Write-Host "Several Firefox profiles found:"
  for ($i = 0; $i -lt $candidates.Count; $i++) { Write-Host ("  {0}) {1}" -f ($i + 1), $candidates[$i].Name) }
  $pick = [int](Read-Host ("Which one? [1-{0}]" -f $candidates.Count))
  if ($pick -lt 1 -or $pick -gt $candidates.Count) { Write-Error "Out of range." }
  $target = $candidates[$pick - 1]
}

# Replace (or remove) the marked block in a file, keeping everything else.
function Write-Block($path, $begin, $end, $content) {
  New-Item -ItemType Directory -Force -Path (Split-Path $path) | Out-Null
  # A linked file belongs to something else; writing the block would edit that.
  if ((Test-Path $path) -and (Get-Item $path -Force).LinkType) {
    Write-Host "Skipping $path: it is a link, so it is managed elsewhere."
    return
  }
  $text = if (Test-Path $path) { [IO.File]::ReadAllText($path) } else { "" }
  $pattern = [regex]::Escape($begin) + "[\\s\\S]*?" + [regex]::Escape($end) + "\\r?\\n?"
  $text = [regex]::Replace($text, $pattern, "").TrimEnd()
  if (-not $Uninstall) {
    if ($text) { $text += "\`n\`n" }
    $text += "$begin\`n$content\`n$end\`n"
  } elseif ($text) { $text += "\`n" }
  [IO.File]::WriteAllText($path, $text, (New-Object Text.UTF8Encoding $false))
}

$css = @'
${css}
'@

$prefs = @'
${prefs}
'@

# Firefox's own Ctrl+T is a reserved shortcut, so Arc's command bar can only
# have it once the built-in key is cleared. An empty entry in customKeys.json
# means "cleared"; other entries there are left alone.
$keysPath = Join-Path $target.FullName "customKeys.json"
$keys = [ordered]@{}
if (Test-Path $keysPath) {
  $raw = (Get-Content $keysPath -Raw).Trim()
  if ($raw) { try { (ConvertFrom-Json $raw).PSObject.Properties | ForEach-Object { $keys[$_.Name] = $_.Value } } catch {} }
}
foreach ($key in @("key_newNavigatorTab", "key_close")) {
  if ($Uninstall) { $keys.Remove($key) }
  elseif (-not $keys.Contains($key)) { $keys[$key] = @{} }
}
[IO.File]::WriteAllText($keysPath, (ConvertTo-Json $keys -Compress -Depth 5), (New-Object Text.UTF8Encoding $false))

Write-Block (Join-Path $target.FullName "chrome\\userChrome.css") $CssBegin $CssEnd $css
Write-Block (Join-Path $target.FullName "user.js") $JsBegin $JsEnd $prefs

if ($Uninstall) {
  Write-Host "Removed Arc's layout from $($target.Name). Restart Firefox."
} else {
  Write-Host "Arc's layout is set up in $($target.Name). Quit Firefox completely and open it again."
}
`;

fs.mkdirSync("extras/setup", { recursive: true });
// Plain .txt inside the add-on: add-on review flags any ".sh" in a file name.
// The download is named arc-setup.sh.
fs.writeFileSync("extras/setup/arc-setup.txt", sh);
fs.writeFileSync("extras/setup/arc-setup.ps1", ps1.replace(/\n/g, "\r\n"));
console.log("wrote extras/setup/arc-setup.txt and extras/setup/arc-setup.ps1");
