# Arc for Firefox: give Arc the whole window (Windows).
#
# Adds Arc's layout to the Firefox profile that has Arc installed:
#   <profile>\chrome\userChrome.css  hides Firefox's tab strip and toolbar
#   <profile>\user.js                turns the stylesheet on, horizontal tabs,
#                                    opens Arc at startup
# Your own CSS and prefs are kept: Arc only manages its marked block.
#
# Usage:  powershell -ExecutionPolicy Bypass -File arc-setup.ps1             set up (or update)
#         powershell -ExecutionPolicy Bypass -File arc-setup.ps1 -Uninstall  remove Arc's blocks
# Generated by scripts/build-setup.mjs; edit extras/ instead.
param([switch]$Uninstall)
$ErrorActionPreference = "Stop"

$AddonId = "arc@sidebar"
$CssBegin = "/* >>> Arc for Firefox >>> */"
$CssEnd = "/* <<< Arc for Firefox <<< */"
$JsBegin = "// >>> Arc for Firefox >>>"
$JsEnd = "// <<< Arc for Firefox <<<"

$root = Join-Path $env:APPDATA "Mozilla\Firefox\Profiles"
if (-not (Test-Path $root)) { Write-Error "No Firefox profiles found in $root" }

$all = @(Get-ChildItem $root -Directory | Where-Object { Test-Path (Join-Path $_.FullName "prefs.js") })
$arc = @($all | Where-Object {
  $ext = Join-Path $_.FullName "extensions.json"
  (Test-Path $ext) -and ((Get-Content $ext -Raw) -match [regex]::Escape('"id":"' + $AddonId + '"'))
})

if ($arc.Count -gt 0) { $candidates = $arc } else {
  Write-Host "No Firefox profile with Arc installed was found. Install Arc first, or pick a profile:"
  $candidates = $all
}
if ($candidates.Count -eq 0) { Write-Error "No Firefox profiles found." }

$target = $candidates[0]
if ($candidates.Count -gt 1) {
  Write-Host "Several Firefox profiles found:"
  for ($i = 0; $i -lt $candidates.Count; $i++) { Write-Host ("  {0}) {1}" -f ($i + 1), $candidates[$i].Name) }
  $pick = [int](Read-Host ("Which one? [1-{0}]" -f $candidates.Count))
  if ($pick -lt 1 -or $pick -gt $candidates.Count) { Write-Error "Out of range." }
  $target = $candidates[$pick - 1]
}

# Replace (or remove) the marked block in a file, keeping everything else.
function Write-Block($path, $begin, $end, $content) {
  New-Item -ItemType Directory -Force -Path (Split-Path $path) | Out-Null
  $text = if (Test-Path $path) { [IO.File]::ReadAllText($path) } else { "" }
  $pattern = [regex]::Escape($begin) + "[\s\S]*?" + [regex]::Escape($end) + "\r?\n?"
  $text = [regex]::Replace($text, $pattern, "").TrimEnd()
  if (-not $Uninstall) {
    if ($text) { $text += "`n`n" }
    $text += "$begin`n$content`n$end`n"
  } elseif ($text) { $text += "`n" }
  [IO.File]::WriteAllText($path, $text, (New-Object Text.UTF8Encoding $false))
}

$css = @'
/*
 * ArcFox layout for Firefox. Always on: ArcFox's sidebar replaces the tab strip
 * and toolbar. Firefox's pinned extension buttons (+ extensions and main menu
 * buttons) become a row of tiles in the sidebar, above the ArcFox address bar.
 *
 * Setup (pair with extras/user.js, which also opens ArcFox at startup):
 *   1. about:support -> Profile Folder -> Open. Create a "chrome" folder there.
 *   2. Copy this file into it as chrome/userChrome.css.
 *   3. Copy extras/user.js into the profile folder, then restart Firefox.
 * Which extensions show: pin/unpin them via the puzzle-piece menu.
 * Tip: remap ArcFox's "Focus the address bar" to Cmd/Ctrl+L in
 *      about:addons -> gear -> Manage Extension Shortcuts.
 */

:root {
  --arcfox-sidebar-width: 260px;
  /* Draggable title-bar patch at the sidebar's top-left (window buttons). */
  --arcfox-titlebar-width: 150px;
  /* Must match ArcFox's layout: row starts 40px into the sidebar, 30px tall. */
  --arcfox-ext-top: 40px;
  --arcfox-ext-height: 30px;
  --arcfox-ext-tile: rgba(255, 255, 255, 0.22);
  --arcfox-ext-hover: rgba(0, 0, 0, 0.06);
  --arcfox-ext-active: rgba(0, 0, 0, 0.1);
}

@media (prefers-color-scheme: dark) {
  :root {
    --arcfox-ext-tile: rgba(255, 255, 255, 0.06);
    --arcfox-ext-hover: rgba(255, 255, 255, 0.11);
    --arcfox-ext-active: rgba(255, 255, 255, 0.16);
  }
}

/* ---------- Firefox chrome ArcFox replaces ---------- */

/* Firefox's sidebar launcher and the panel header ("Arc  x"):
   #sidebar-header in the old sidebar; #sidebar-panel-header in the new one,
   which lives inside the panel document (webext-panels.xhtml). */
#sidebar-panel-header,
#sidebar-container,
#sidebar-launcher-splitter,
#sidebar-header,
#sidebar-splitter {
  visibility: collapse !important;
  display: none !important;
}

/* What's left of the tab strip: a transparent patch in the sidebar's empty
   top-left corner (Arc's nav buttons sit on the right). It keeps the macOS
   window buttons, window dragging and double-click to zoom. The tabs stay
   hidden; Arc lists them. */
#TabsToolbar {
  position: fixed !important;
  z-index: 4 !important;
  top: 0 !important;
  left: 0 !important;
  width: var(--arcfox-titlebar-width) !important;
  height: var(--arcfox-ext-top) !important;
  min-height: 0 !important;
  margin: 0 !important;
  border: 0 !important;
  background: transparent !important;
}
#TabsToolbar > .toolbar-items,
#TabsToolbar .private-browsing-indicator-with-label {
  visibility: collapse !important;
}

/* Sharp edge between Arc and the page: Firefox rounds and shadows both the
   sidebar panel and the content area. */
#sidebar,
#sidebar-box,
.sidebar-browser-stack,
#tabbrowser-tabbox,
#tabbrowser-tabpanels,
.browserSidebarContainer,
.browserContainer,
.browserStack,
#tabbrowser-tabpanels browser {
  border-radius: 0 !important;
  border: none !important;
  outline: none !important;
  box-shadow: none !important;
  margin: 0 !important;
}

/* Firefox leaves a gap under the sidebar (padding-block-end); Arc fills it. */
#sidebar-box,
#sidebar-container,
.sidebar-browser-stack {
  padding: 0 !important;
}

/* The separator line itself (Firefox draws it as a border on the sidebar). */
:root {
  --sidebar-border-color: transparent !important;
  --chrome-content-separator-color: transparent !important;
}

/* Fixed width so the extensions row lines up with the sidebar. */
#sidebar-box {
  width: var(--arcfox-sidebar-width) !important;
  min-width: var(--arcfox-sidebar-width) !important;
  max-width: var(--arcfox-sidebar-width) !important;
}

/* Arc's own small windows (command bar, space editor) are popups: no toolbar. */
#main-window[chromehidden~="toolbar"] #nav-bar {
  display: none !important;
}

/* ---------- Toolbar -> extensions row inside the sidebar ---------- */

/* Sidebar hidden with Option+Shift+S (Arc sets an invisible window-title marker),
   or closed: the page goes full width and the extensions row hides too. */
#main-window[titlepreface="\200B"] :is(#sidebar-box, #nav-bar),
#main-window:has(#sidebar-box[hidden]) #nav-bar {
  display: none !important;
}

/* The toolbox forms its own stacking context; lift it above the sidebar. */
#navigator-toolbox {
  position: relative !important;
  z-index: 10 !important;
}

#nav-bar {
  position: fixed !important;
  z-index: 3 !important;
  top: var(--arcfox-ext-top) !important;
  left: 8px !important;
  width: calc(var(--arcfox-sidebar-width) - 16px) !important;
  height: var(--arcfox-ext-height) !important;
  min-height: 0 !important;
  margin: 0 !important;
  padding: 0 !important;
  border: 0 !important;
  background: transparent !important;
  box-shadow: none !important;
  --toolbarbutton-outer-padding: 0px;
  --toolbarbutton-inner-padding: 7px;
  --toolbarbutton-border-radius: 8px;
  --toolbarbutton-hover-background: var(--arcfox-ext-hover);
  --toolbarbutton-active-background: var(--arcfox-ext-active);
  --toolbar-start-end-padding: 0px;
}

/* Flatten the button group so every button is an equal tile in one row. */
#nav-bar-customization-target {
  display: contents !important;
}

/* Keep only extension buttons (never Arc's own), extensions menu, main menu,
   and the (off-screen) address bar below. */
#nav-bar-customization-target > :not(.unified-extensions-item, .webextension-browser-action, #unified-extensions-button, #urlbar-container),
#nav-bar .webextension-browser-action[id^="arc_sidebar"],
#nav-bar-overflow-button,
#nav-bar > :not(#nav-bar-customization-target, #unified-extensions-button, #PanelUI-button) {
  display: none !important;
}

#nav-bar :is(.unified-extensions-item, .webextension-browser-action),
#unified-extensions-button,
#PanelUI-button {
  flex: 1 1 0 !important;
  min-width: 0 !important;
  margin: 0 !important;
  margin-inline-start: 4px !important;
  height: var(--arcfox-ext-height) !important;
}
#nav-bar :is(.unified-extensions-item, .webextension-browser-action, #unified-extensions-button, #PanelUI-button):not([hidden]):first-of-type {
  margin-inline-start: 0 !important;
}
#PanelUI-button {
  padding: 0 !important;
  border: 0 !important;
}

/* The tile: stretch each button's visual box across its slot. */
#nav-bar :is(.unified-extensions-item, .webextension-browser-action) .toolbarbutton-1,
#unified-extensions-button,
#PanelUI-menu-button {
  width: 100% !important;
  height: var(--arcfox-ext-height) !important;
  padding: 0 !important;
  justify-content: center !important;
}
#nav-bar :is(.unified-extensions-item, .webextension-browser-action) .toolbarbutton-1 > :is(.toolbarbutton-badge-stack, .toolbarbutton-icon),
#unified-extensions-button > .toolbarbutton-icon,
#PanelUI-menu-button > :is(.toolbarbutton-badge-stack, .toolbarbutton-icon) {
  width: 100% !important;
  height: var(--arcfox-ext-height) !important;
  padding-block: calc((var(--arcfox-ext-height) - 16px) / 2) !important;
  padding-inline: calc(50% - 8px) !important;
  border-radius: 8px !important;
  background-color: var(--arcfox-ext-tile);
  justify-content: center !important;
}
#nav-bar .toolbarbutton-1:not([disabled]):hover > :is(.toolbarbutton-badge-stack, .toolbarbutton-icon) {
  background-color: var(--arcfox-ext-hover) !important;
}
#nav-bar .toolbarbutton-1:not([disabled]):is([open], [checked], :hover:active) > :is(.toolbarbutton-badge-stack, .toolbarbutton-icon) {
  background-color: var(--arcfox-ext-active) !important;
}

/* ---------- Firefox's address bar: hidden until Cmd/Ctrl+L ----------
   Arc has its own address bar, but Firefox pages (about:config, ...) can only
   be opened from Firefox's. It waits off-screen and shows as a centered bar
   while focused. */
#urlbar-container {
  position: fixed !important;
  z-index: 30 !important;
  top: -400px !important;
  left: 50% !important;
  width: min(680px, 70vw) !important;
  max-width: none !important;
  margin: 0 !important;
  transform: translateX(-50%);
}
#urlbar-container:focus-within {
  top: 16vh !important;
}
#urlbar-container:focus-within #urlbar-background {
  box-shadow: 0 16px 48px rgba(0, 0, 0, 0.25), 0 0 0 1px rgba(0, 0, 0, 0.08) !important;
}
'@

$prefs = @'
// ArcFox: copy into your Firefox profile folder (next to prefs.js).
// Firefox applies these on every start.

// Load chrome/userChrome.css.
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
// Horizontal tabs (their strip is hidden; ArcFox lists the tabs).
user_pref("sidebar.verticalTabs", false);
// Closing the last tab keeps the window (with a new tab), like Arc.
user_pref("browser.tabs.closeWindowWithLastTab", false);
// Reopen windows and tabs, including the open ArcFox sidebar.
user_pref("browser.startup.page", 3);
// Fallback when there is no session to restore: ArcFox panel open, launcher hidden.
user_pref("sidebar.backupState", "{\"command\":\"arc_sidebar-sidebar-action\",\"panelOpen\":true,\"panelWidth\":260,\"launcherVisible\":false,\"launcherExpanded\":false}");
'@

Write-Block (Join-Path $target.FullName "chrome\userChrome.css") $CssBegin $CssEnd $css
Write-Block (Join-Path $target.FullName "user.js") $JsBegin $JsEnd $prefs

if ($Uninstall) {
  Write-Host "Removed Arc's layout from $($target.Name). Restart Firefox."
} else {
  Write-Host "Arc's layout is set up in $($target.Name). Quit Firefox completely and open it again."
}
