# Arc for Firefox: give Arc the whole window (Windows).
#
# Adds Arc's layout to the Firefox profile that has Arc installed:
#   <profile>\chrome\userChrome.css  hides Firefox's tab strip and toolbar
#   <profile>\user.js                turns the stylesheet on, horizontal tabs,
#                                    opens Arc at startup
#   <profile>\customKeys.json        clears Firefox's Ctrl+T and Ctrl+W so Arc
#                                    can handle them
# Your own CSS and prefs are kept: Arc only manages its marked block.
#
# Usage:  powershell -ExecutionPolicy Bypass -File arc-setup.ps1             set up (or update)
#         powershell -ExecutionPolicy Bypass -File arc-setup.ps1 -Uninstall  remove Arc's blocks
# Generated by scripts/build-setup.mjs; edit extras/ instead.
param([switch]$Uninstall)
$ErrorActionPreference = "Stop"

$AddonId = "arc@sidebar"
$CssBegin = "/* >>> Arc for Firefox >>> */"
$CssEnd = "/* <<< Arc for Firefox <<< */"
$JsBegin = "// >>> Arc for Firefox >>>"
$JsEnd = "// <<< Arc for Firefox <<<"

$root = Join-Path $env:APPDATA "Mozilla\Firefox\Profiles"
if (-not (Test-Path $root)) { Write-Error "No Firefox profiles found in $root" }

$all = @(Get-ChildItem $root -Directory | Where-Object { Test-Path (Join-Path $_.FullName "prefs.js") })
$arc = @($all | Where-Object {
  $ext = Join-Path $_.FullName "extensions.json"
  (Test-Path $ext) -and ((Get-Content $ext -Raw) -match [regex]::Escape('"id":"' + $AddonId + '"'))
})

if ($arc.Count -gt 0) { $candidates = $arc } else {
  Write-Host "No Firefox profile with Arc installed was found. Install Arc first, or pick a profile:"
  $candidates = $all
}
if ($candidates.Count -eq 0) { Write-Error "No Firefox profiles found." }

$target = $candidates[0]
if ($candidates.Count -gt 1) {
  Write-Host "Several Firefox profiles found:"
  for ($i = 0; $i -lt $candidates.Count; $i++) { Write-Host ("  {0}) {1}" -f ($i + 1), $candidates[$i].Name) }
  $pick = [int](Read-Host ("Which one? [1-{0}]" -f $candidates.Count))
  if ($pick -lt 1 -or $pick -gt $candidates.Count) { Write-Error "Out of range." }
  $target = $candidates[$pick - 1]
}

# Replace (or remove) the marked block in a file, keeping everything else.
function Write-Block($path, $begin, $end, $content) {
  New-Item -ItemType Directory -Force -Path (Split-Path $path) | Out-Null
  # A linked file belongs to something else; writing the block would edit that.
  if ((Test-Path $path) -and (Get-Item $path -Force).LinkType) {
    Write-Host "Skipping $path: it is a link, so it is managed elsewhere."
    return
  }
  $text = if (Test-Path $path) { [IO.File]::ReadAllText($path) } else { "" }
  $pattern = [regex]::Escape($begin) + "[\s\S]*?" + [regex]::Escape($end) + "\r?\n?"
  $text = [regex]::Replace($text, $pattern, "").TrimEnd()
  if (-not $Uninstall) {
    if ($text) { $text += "`n`n" }
    $text += "$begin`n$content`n$end`n"
  } elseif ($text) { $text += "`n" }
  [IO.File]::WriteAllText($path, $text, (New-Object Text.UTF8Encoding $false))
}

$css = @'
/*
 * ArcFox layout for Firefox. Always on: ArcFox's sidebar replaces the tab strip
 * and toolbar. Firefox's pinned extension buttons (+ extensions and main menu
 * buttons) become a row of tiles in the sidebar, above the ArcFox address bar.
 *
 * Setup (pair with extras/user.js, which also opens ArcFox at startup):
 *   1. about:support -> Profile Folder -> Open. Create a "chrome" folder there.
 *   2. Copy this file into it as chrome/userChrome.css.
 *   3. Copy extras/user.js into the profile folder, then restart Firefox.
 * Which extensions show: pin/unpin them via the puzzle-piece menu.
 * Tip: remap ArcFox's "Focus the address bar" to Cmd/Ctrl+L in
 *      about:addons -> gear -> Manage Extension Shortcuts.
 */

:root {
  /* Starting width only: drag the edge to resize, Firefox remembers it. */
  --arcfox-sidebar-width: 260px;
  --arcfox-sidebar-min: 180px;
  --arcfox-sidebar-max: 620px;
  /* Draggable title-bar patch at the sidebar's top-left (window buttons). */
  --arcfox-titlebar-width: 150px;
  /* Must match ArcFox's layout: row starts 40px into the sidebar, 30px tall. */
  --arcfox-ext-top: 40px;
  --arcfox-ext-height: 30px;
  --arcfox-ext-tile: rgba(255, 255, 255, 0.22);
  --arcfox-ext-hover: rgba(0, 0, 0, 0.06);
  --arcfox-ext-active: rgba(0, 0, 0, 0.1);
}

@media (prefers-color-scheme: dark) {
  :root {
    --arcfox-ext-tile: rgba(255, 255, 255, 0.06);
    --arcfox-ext-hover: rgba(255, 255, 255, 0.11);
    --arcfox-ext-active: rgba(255, 255, 255, 0.16);
  }
}

/* ---------- Arc's background, for Firefox's own panels ---------- */

/* Arc tints its sidebar with the current space's color. Firefox's panels are
   chrome and can't read that, so Arc writes the color into the window title
   as an invisible marker (background.js) and it's decoded here. Values mirror
   shared/theme.css. */
:root {
  --arcfox-base: #efedf5;
  --arcfox-tint: 16%;
  --arcfox-space: #af51f5;
  --arcfox-panel-bg: color-mix(in srgb, var(--arcfox-space) var(--arcfox-tint), var(--arcfox-base));
}

@media (prefers-color-scheme: dark) {
  :root {
    --arcfox-base: #1c1a22;
    --arcfox-tint: 12%;
  }
}

#main-window[titlepreface*="\200C"] { --arcfox-space: #37adff; } /* blue */
#main-window[titlepreface*="\200D"] { --arcfox-space: #00c79a; } /* turquoise */
#main-window[titlepreface*="\2060"] { --arcfox-space: #51cd00; } /* green */
#main-window[titlepreface*="\2061"] { --arcfox-space: #ffcb00; } /* yellow */
#main-window[titlepreface*="\2062"] { --arcfox-space: #ff9f00; } /* orange */
#main-window[titlepreface*="\2063"] { --arcfox-space: #ff613d; } /* red */
#main-window[titlepreface*="\2064"] { --arcfox-space: #ff4bda; } /* pink */
#main-window[titlepreface*="\FEFF"] { --arcfox-space: #af51f5; } /* purple */

/* The panel area carries the color; Firefox's panels then let it through. */
#sidebar-box,
#sidebar {
  background-color: var(--arcfox-panel-bg) !important;
}
:root {
  --sidebar-background-color: var(--arcfox-panel-bg) !important;
}

@-moz-document url-prefix("chrome://browser/content/places/"),
  url-prefix("chrome://browser/content/syncedtabs/"),
  url-prefix("chrome://browser/content/genai/"),
  url-prefix("chrome://browser/content/sidebar/") {
  :root,
  body,
  #sidebar-panel-header,
  #history-panel,
  #bookmarksPanel,
  #syncedTabsContent,
  tree,
  tree > treechildren {
    background: transparent !important;
    background-color: transparent !important;
  }
}

/* ---------- Firefox chrome ArcFox replaces ---------- */

/* Firefox's sidebar launcher and the panel header ("Arc  x"):
   #sidebar-header in the old sidebar; #sidebar-panel-header in the new one,
   which lives inside the panel document (webext-panels.xhtml). */
#sidebar-container,
#sidebar-launcher-splitter,
#sidebar-header {
  visibility: collapse !important;
  display: none !important;
}

/* Arc's sidebar is resizable: Firefox's splitter stays, as an invisible grab
   strip on the edge (it draws the border Arc removed otherwise). Firefox
   remembers the width it's dragged to. */
#sidebar-splitter {
  /* No display override: a <splitter> drags because of its own frame, and
     forcing a CSS display (flex) replaces that frame — the strip then looks
     right but stops resizing once the page lays out. Visibility is stated
     because an older copy of this file collapses the splitter. */
  visibility: visible !important;
  appearance: none !important;
  width: 8px !important;
  min-width: 8px !important;
  /* Entirely over the sidebar: the half that used to hang into the content
     area sits above a remote page, which swallows the drag once it loads. */
  margin-inline-start: -8px !important;
  margin-inline-end: 0 !important;
  pointer-events: auto !important;
  border: 0 !important;
  background: transparent !important;
  cursor: col-resize !important;
  z-index: 11 !important;
}

/* No sidebar, no edge to drag (Option+Shift+S, or the panel closed): the strip
   would otherwise sit over the page and swallow clicks. */
#main-window[titlepreface*="\200B"] #sidebar-splitter,
#sidebar-box[hidden] + #sidebar-splitter {
  display: none !important;
}

/* The panel header belongs to the panel's own document, and userChrome.css
   styles every chrome document — so hide it only in Arc's panel. Firefox's
   own panels (bookmarks, history, synced tabs, AI chat) keep their title
   and close button. */
@-moz-document url-prefix("chrome://browser/content/webext-panels.xhtml") {
  #sidebar-panel-header {
    visibility: collapse !important;
    display: none !important;
  }
}

/* What's left of the tab strip: a transparent patch in the sidebar's empty
   top-left corner (Arc's nav buttons sit on the right). It keeps the macOS
   window buttons, window dragging and double-click to zoom. The tabs stay
   hidden; Arc lists them. */
#TabsToolbar {
  position: fixed !important;
  z-index: 4 !important;
  top: 0 !important;
  left: 0 !important;
  width: var(--arcfox-titlebar-width) !important;
  height: var(--arcfox-ext-top) !important;
  min-height: 0 !important;
  margin: 0 !important;
  border: 0 !important;
  background: transparent !important;
}
#TabsToolbar > .toolbar-items,
#TabsToolbar .private-browsing-indicator-with-label {
  visibility: collapse !important;
}

/* Sharp edge between Arc and the page: Firefox rounds and shadows both the
   sidebar panel and the content area. */
#sidebar,
#sidebar-box,
.sidebar-browser-stack,
#tabbrowser-tabbox,
#tabbrowser-tabpanels,
.browserSidebarContainer,
.browserContainer,
.browserStack,
#tabbrowser-tabpanels browser {
  border-radius: 0 !important;
  border: none !important;
  outline: none !important;
  box-shadow: none !important;
  margin: 0 !important;
}

/* Firefox leaves a gap under the sidebar (padding-block-end); Arc fills it. */
#sidebar-box,
#sidebar-container,
.sidebar-browser-stack {
  padding: 0 !important;
}

/* The separator line itself (Firefox draws it as a border on the sidebar). */
:root {
  --sidebar-border-color: transparent !important;
  --chrome-content-separator-color: transparent !important;
}

/* Fixed width so the extensions row lines up with the sidebar. */
#sidebar-box {
  width: var(--arcfox-sidebar-width);
  min-width: var(--arcfox-sidebar-min) !important;
  max-width: var(--arcfox-sidebar-max) !important;
}

/* ---------- Firefox's own sidebar panels ---------- */

/* Arc's layout is made for Arc's panel (which Firefox loads as
   webext-panels.xhtml). When the sidebar shows one of Firefox's panels
   instead, hand the space back: the extensions row would sit on the panel's
   search field, the window buttons would cover its first row, and Arc's
   narrow width crops the AI chat. */
#main-window:has(#sidebar[src]:not([src*="webext-panels"]):not([src="about:blank"])) {
  --arcfox-native-panel: 1;
}
#main-window:has(#sidebar[src]:not([src*="webext-panels"]):not([src="about:blank"])) #nav-bar {
  display: none !important;
}
#main-window:has(#sidebar[src]:not([src*="webext-panels"]):not([src="about:blank"])) #sidebar-box {
  /* Same width as Arc's own panel (drag the edge to change both). Firefox
     asks for 400px for the AI chat; Arc's width wins. */
  min-width: var(--arcfox-sidebar-min) !important;
  padding-block-start: var(--arcfox-ext-top) !important;
}

/* Arc's own small windows (command bar, space editor) are popups: no toolbar. */
#main-window[chromehidden~="toolbar"] #nav-bar {
  display: none !important;
}

/* ---------- Toolbar -> extensions row inside the sidebar ---------- */

/* Sidebar hidden with Option+Shift+S (Arc sets an invisible window-title marker),
   or closed: the page goes full width and the extensions row hides too. */
#main-window[titlepreface="\200B"] :is(#sidebar-box, #nav-bar),
#main-window:has(#sidebar-box[hidden]) #nav-bar {
  display: none !important;
}

/* The toolbox forms its own stacking context; lift it above the sidebar. */
#navigator-toolbox {
  position: relative !important;
  z-index: 10 !important;
}

#nav-bar {
  position: fixed !important;
  z-index: 3 !important;
  top: var(--arcfox-ext-top) !important;
  left: 8px !important;
  width: calc(var(--arcfox-sidebar-width) - 16px) !important;
  max-width: calc(100vw - 16px) !important;
  height: var(--arcfox-ext-height) !important;
  min-height: 0 !important;
  margin: 0 !important;
  padding: 0 !important;
  border: 0 !important;
  background: transparent !important;
  box-shadow: none !important;
  --toolbarbutton-outer-padding: 0px;
  --toolbarbutton-inner-padding: 7px;
  --toolbarbutton-border-radius: 8px;
  --toolbarbutton-hover-background: var(--arcfox-ext-hover);
  --toolbarbutton-active-background: var(--arcfox-ext-active);
  --toolbar-start-end-padding: 0px;
}

/* Flatten the button group so every button is an equal tile in one row. */
#nav-bar-customization-target {
  display: contents !important;
}

/* Keep only extension buttons (never Arc's own), extensions menu, main menu,
   and the (off-screen) address bar below. */
#nav-bar-customization-target > :not(.unified-extensions-item, .webextension-browser-action, #unified-extensions-button, #urlbar-container),
#nav-bar .webextension-browser-action[id^="arc_sidebar"],
#nav-bar-overflow-button,
#nav-bar > :not(#nav-bar-customization-target, #unified-extensions-button, #PanelUI-button) {
  display: none !important;
}

#nav-bar :is(.unified-extensions-item, .webextension-browser-action),
#unified-extensions-button,
#PanelUI-button {
  flex: 1 1 0 !important;
  min-width: 0 !important;
  margin: 0 !important;
  margin-inline-start: 4px !important;
  height: var(--arcfox-ext-height) !important;
}
#nav-bar :is(.unified-extensions-item, .webextension-browser-action, #unified-extensions-button, #PanelUI-button):not([hidden]):first-of-type {
  margin-inline-start: 0 !important;
}
#PanelUI-button {
  padding: 0 !important;
  border: 0 !important;
}

/* The tile: stretch each button's visual box across its slot. */
#nav-bar :is(.unified-extensions-item, .webextension-browser-action) .toolbarbutton-1,
#unified-extensions-button,
#PanelUI-menu-button {
  width: 100% !important;
  height: var(--arcfox-ext-height) !important;
  padding: 0 !important;
  justify-content: center !important;
}
#nav-bar :is(.unified-extensions-item, .webextension-browser-action) .toolbarbutton-1 > :is(.toolbarbutton-badge-stack, .toolbarbutton-icon),
#unified-extensions-button > .toolbarbutton-icon,
#PanelUI-menu-button > :is(.toolbarbutton-badge-stack, .toolbarbutton-icon) {
  width: 100% !important;
  height: var(--arcfox-ext-height) !important;
  padding-block: calc((var(--arcfox-ext-height) - 16px) / 2) !important;
  padding-inline: calc(50% - 8px) !important;
  border-radius: 8px !important;
  background-color: var(--arcfox-ext-tile);
  justify-content: center !important;
}
#nav-bar .toolbarbutton-1:not([disabled]):hover > :is(.toolbarbutton-badge-stack, .toolbarbutton-icon) {
  background-color: var(--arcfox-ext-hover) !important;
}
#nav-bar .toolbarbutton-1:not([disabled]):is([open], [checked], :hover:active) > :is(.toolbarbutton-badge-stack, .toolbarbutton-icon) {
  background-color: var(--arcfox-ext-active) !important;
}

/* ---------- Firefox's address bar: hidden until Cmd/Ctrl+L ----------
   Arc has its own address bar, but Firefox pages (about:config, ...) can only
   be opened from Firefox's. It waits off-screen and shows as a centered bar
   while focused. */
#urlbar-container {
  position: fixed !important;
  z-index: 30 !important;
  top: -400px !important;
  left: 50% !important;
  width: min(680px, 70vw) !important;
  max-width: none !important;
  margin: 0 !important;
  transform: translateX(-50%);
}
#urlbar-container:focus-within {
  top: 16vh !important;
}
#urlbar-container:focus-within #urlbar-background {
  box-shadow: 0 16px 48px rgba(0, 0, 0, 0.25), 0 0 0 1px rgba(0, 0, 0, 0.08) !important;
}

/* The extensions row lives in the toolbar, outside the sidebar, so it can't
   read the sidebar's width. Where anchor positioning is available it tracks
   the sidebar's edges exactly; otherwise it keeps its default width and the
   row simply stays left-aligned when the sidebar is dragged wider. */
@supports (position-anchor: --a) {
  #sidebar-box {
    anchor-name: --arcfox-sidebar !important;
  }
  #nav-bar {
    position-anchor: --arcfox-sidebar !important;
    left: calc(anchor(left) + 8px) !important;
    right: calc(anchor(right) + 8px) !important;
    width: auto !important;
  }
}
'@

$prefs = @'
// ArcFox: copy into your Firefox profile folder (next to prefs.js).
// Firefox applies these on every start.

// Load chrome/userChrome.css.
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
// Horizontal tabs (their strip is hidden; ArcFox lists the tabs).
user_pref("sidebar.verticalTabs", false);
// Closing the last tab keeps the window (with a new tab), like Arc.
user_pref("browser.tabs.closeWindowWithLastTab", false);
// Reopen windows and tabs, including the open ArcFox sidebar.
user_pref("browser.startup.page", 3);
// Arc's panel state (open, and how wide) lives in sidebar.backupState, which
// Firefox writes itself. The setup seeds it once in prefs.js instead of here:
// a user_pref would be re-applied at every start, throwing away a width the
// sidebar had been dragged to.
'@

# Firefox's own Ctrl+T is a reserved shortcut, so Arc's command bar can only
# have it once the built-in key is cleared. An empty entry in customKeys.json
# means "cleared"; other entries there are left alone.
$keysPath = Join-Path $target.FullName "customKeys.json"
$keys = [ordered]@{}
if (Test-Path $keysPath) {
  $raw = (Get-Content $keysPath -Raw).Trim()
  if ($raw) { try { (ConvertFrom-Json $raw).PSObject.Properties | ForEach-Object { $keys[$_.Name] = $_.Value } } catch {} }
}
foreach ($key in @("key_newNavigatorTab", "key_close")) {
  if ($Uninstall) { $keys.Remove($key) }
  elseif (-not $keys.Contains($key)) { $keys[$key] = @{} }
}
[IO.File]::WriteAllText($keysPath, (ConvertTo-Json $keys -Compress -Depth 5), (New-Object Text.UTF8Encoding $false))

# An Arc stylesheet outside Arc's block is an older copy from a manual
# install: it keeps applying, and rules the new block doesn't restate win.
$cssPath = Join-Path $target.FullName "chrome\userChrome.css"
if ((Test-Path $cssPath)) {
  $existing = Get-Content $cssPath -Raw
  if ($existing -match "arcfox-sidebar-width" -and -not $existing.Contains($CssBegin)) {
    Write-Host "Note: chrome\userChrome.css already has an Arc stylesheet outside Arc's block."
    Write-Host "      Remove that older copy, or the two will fight."
  }
}

Write-Block $cssPath $CssBegin $CssEnd $css
Write-Block (Join-Path $target.FullName "user.js") $JsBegin $JsEnd $prefs

# Open Arc's panel on a profile that has never had it open. This goes into
# prefs.js, which Firefox owns from then on: it records the width the sidebar
# is dragged to, and a user_pref would overwrite that at every start.
# Injected verbatim into the setup scripts by scripts/build-setup.mjs.
$prefsPath = Join-Path $target.FullName "prefs.js"
if (-not $Uninstall -and (Test-Path $prefsPath) -and -not ((Get-Content $prefsPath -Raw) -match 'sidebar\.backupState')) {
  $seed = 'user_pref("sidebar.backupState", "{\"command\":\"arc_sidebar-sidebar-action\",\"panelOpen\":true,\"launcherVisible\":false,\"launcherExpanded\":false}");'
  Add-Content $prefsPath $seed
  Write-Host "Seeded sidebar.backupState so Arc's panel opens; Firefox keeps its width from now on."
}

if ($Uninstall) {
  Write-Host "Removed Arc's layout from $($target.Name). Restart Firefox."
} else {
  Write-Host "Arc's layout is set up in $($target.Name). Quit Firefox completely and open it again."
}
